####
# This Dockerfile is used to package the yak-server application
#
# Build the image with:
#
# ./gradlew buildDocker
#
###

#FROM openjdk:18-jdk-alpine3.14 AS jre-build
FROM openjdk:17-slim-bullseye AS jre-build

WORKDIR /home/app

## copy the dependencies into the docker image
COPY layers/libs /home/app/libs

## copy the app resources
COPY layers/resources /home/app/resources

## copy the executable jar into the docker image
COPY layers/application.jar /home/app/application.jar

## default port of the application
EXPOSE 8080

#ENTRYPOINT ["java", "-jar", "/home/app/application.jar"]
# find JDK dependencies dynamically from jar
RUN jdeps \
  # dont worry about missing modules
    --ignore-missing-deps \
    # suppress any warnings printed to console
    -q \
    # java release version targeting
    --multi-release 17 \
    # output the dependencies at end of run
    --print-module-deps \
    # specify the the dependencies for the jar
    --class-path /home/app/libs/* \
    # pipe the result of running jdeps on the app jar to file
    /home/app/application.jar > jre-deps.info

## temp print jdeps output
#ENTRYPOINT cat /home/app/jre-deps.info
# new since last time!
RUN jlink --verbose \
--compress 2 \
--strip-java-debug-attributes \
--no-header-files \
--no-man-pages \
--output jre \
--add-modules $(cat jre-deps.info)

# take a smaller runtime image for the final output
#FROM alpine:3.14
FROM debian:bullseye-slim

ENV JAVA_HOME /opt/java/openjdk
ENV PATH $JAVA_HOME/bin:$PATH

ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en' LC_ALL='en_US.UTF-8'
# https://github.com/Docker-Hub-frolvlad/docker-alpine-glibc

WORKDIR /home/app

## copy the custom JRE produced from jlink
COPY --from=jre-build /home/app/jre $JAVA_HOME

## copy the app dependencies
COPY --from=jre-build /home/app/libs/* /home/app/libs/

COPY --from=jre-build /home/app/resources/* /home/app/resources

## copy the app
COPY --from=jre-build /home/app/application.jar /home/app/application.jar

## run the app on startup
#ENTRYPOINT [ "/bin/bash" ]
ENTRYPOINT ["java", "-jar", "/home/app/application.jar"]